steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
# Generate .env to build react app.
- name: 'gcr.io/cloud-builders/yarn'
  volumes:
  - name: 'appbuild'
    path: '/appbuild'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    yarn build && \
    cp -R /workspace/build /appbuild/ && \
    cp /workspace/app.yaml /appbuild/
- name: 'gcr.io/cloud-builders/gcloud'
  volumes:
  - name: 'appbuild'
    path: '/appbuild'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    cd /appbuild && \
    gcloud app deploy