steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
# Generate .env to build react app.
- name: 'gcr.io/cloud-builders/yarn'
  args: ["build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]

timeout: "1600s"