steps:
- name: 'gcr.io/cloud-builders/yarn'
  id: yarn_install
  args: ['install']

- name: 'gcr.io/cloud-builders/yarn'
  id: yarn_build
  args: ["build"]

- name: "gcr.io/cloud-builders/gcloud"
  id: deploy
  args: ["app", "deploy"]
