version: 2

jobs:
  build_deploy:
    docker:
      - image: circleci/node:8-jessie-browsers
    working_directory: ~/react-cloud-build
    steps:
      - checkout
      - setup_remote_docker:
         version: 17.06.1-ce
         reusable: true
      # - restore_cache:
      #     key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      # - restore_cache:
      #     key: node-v1-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Yarn Install
          command: yarn install
      # - save_cache:
      #     key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
      #     paths:
      #       - ~/.cache/yarn
      # - save_cache:
      #     key: node-v1-{{ checksum "package.json" }}-{{ arch }}
      #     paths:
      #       - node_modules
      - run:
          name: Yarn Build
          command: |
            yarn build
      # - run: mkdir -p workspace
      # - run:
      #     name: Move build to workspace (shared /w next job)
      #     command: |
      #       cp -R build ./workspace
      #       cp app.yaml ./workspace
      # - run:
      #     name: Store Service Account
      #     command: |
      #       echo ${GOOGLE_AUTH} && echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
      # - run:
      #     name: config GCLOUD SDK
      #     command: |
      #       gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      #       gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      #       gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      # - run:
      #     name: Deploy on app Engine
      #     command: |
      #       cd workspace
      #       gcloud app deploy
      
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_deploy:
          context: gcp-khaly
          filters:
            branches:
              only: master
